[package]
name = "pkr_rename"
version = "0.1.0"
authors = ["User"]
edition = "2018"


[dependencies]
hyper = { version = "0.14", features = ["full"]}
tokio = { version = "1", features = ["full"] }
hyper-tls = { version = "0.5" }